// Code generated by orlop-gen. DO NOT EDIT.

package v1

import (
	_ "embed"

	"github.com/thetechnick/orlop/pkg/apiserver/types"
)

var (
	// ClusterRoleBindingSchemaYAML contains the OpenAPI v3 schema for ClusterRoleBinding.
	//go:embed .schemas/clusterrolebinding_schema.yaml
	ClusterRoleBindingSchemaYAML string

	// ClusterRoleSchemaYAML contains the OpenAPI v3 schema for ClusterRole.
	//go:embed .schemas/clusterrole_schema.yaml
	ClusterRoleSchemaYAML string

	// RoleBindingSchemaYAML contains the OpenAPI v3 schema for RoleBinding.
	//go:embed .schemas/rolebinding_schema.yaml
	RoleBindingSchemaYAML string

	// RoleSchemaYAML contains the OpenAPI v3 schema for Role.
	//go:embed .schemas/role_schema.yaml
	RoleSchemaYAML string

	// SecretSchemaYAML contains the OpenAPI v3 schema for Secret.
	//go:embed .schemas/secret_schema.yaml
	SecretSchemaYAML string

	// ServiceAccountSchemaYAML contains the OpenAPI v3 schema for ServiceAccount.
	//go:embed .schemas/serviceaccount_schema.yaml
	ServiceAccountSchemaYAML string

)

// ClusterRoleBindingResourceInfo describes the ClusterRoleBinding resource type.
var ClusterRoleBindingResourceInfo = types.ResourceInfo{
	GVK:        GroupVersion.WithKind("ClusterRoleBinding"),
	Plural:     "clusterrolebindings",
	Singular:   "clusterrolebinding",
	Namespaced: false,
	SchemaYAML: ClusterRoleBindingSchemaYAML,
}

// ClusterRoleResourceInfo describes the ClusterRole resource type.
var ClusterRoleResourceInfo = types.ResourceInfo{
	GVK:        GroupVersion.WithKind("ClusterRole"),
	Plural:     "clusterroles",
	Singular:   "clusterrole",
	Namespaced: false,
	SchemaYAML: ClusterRoleSchemaYAML,
}

// RoleBindingResourceInfo describes the RoleBinding resource type.
var RoleBindingResourceInfo = types.ResourceInfo{
	GVK:        GroupVersion.WithKind("RoleBinding"),
	Plural:     "rolebindings",
	Singular:   "rolebinding",
	Namespaced: true,
	SchemaYAML: RoleBindingSchemaYAML,
}

// RoleResourceInfo describes the Role resource type.
var RoleResourceInfo = types.ResourceInfo{
	GVK:        GroupVersion.WithKind("Role"),
	Plural:     "roles",
	Singular:   "role",
	Namespaced: true,
	SchemaYAML: RoleSchemaYAML,
}

// SecretResourceInfo describes the Secret resource type.
var SecretResourceInfo = types.ResourceInfo{
	GVK:        GroupVersion.WithKind("Secret"),
	Plural:     "secrets",
	Singular:   "secret",
	Namespaced: true,
	SchemaYAML: SecretSchemaYAML,
}

// ServiceAccountResourceInfo describes the ServiceAccount resource type.
var ServiceAccountResourceInfo = types.ResourceInfo{
	GVK:        GroupVersion.WithKind("ServiceAccount"),
	Plural:     "serviceaccounts",
	Singular:   "serviceaccount",
	Namespaced: true,
	SchemaYAML: ServiceAccountSchemaYAML,
}

// GetResourceInfos returns ResourceInfo definitions for all types in this package.
// This can be used to configure an API server with these resources.
func GetResourceInfos() []types.ResourceInfo {
	return []types.ResourceInfo{
		ClusterRoleBindingResourceInfo,
		ClusterRoleResourceInfo,
		RoleBindingResourceInfo,
		RoleResourceInfo,
		SecretResourceInfo,
		ServiceAccountResourceInfo,
	}
}
