// Code generated by orlop-gen. DO NOT EDIT.

package v1

import (
	_ "embed"

	"github.com/thetechnick/orlop/pkg/apiserver/types"
	apiext "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions"
	apiextv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	"k8s.io/apiextensions-apiserver/pkg/apiserver/schema"
	"sigs.k8s.io/yaml"
)

// ClusterRoleBindingPlural is the plural name for ClusterRoleBinding resources.
const ClusterRoleBindingPlural = "clusterrolebindings"

// ClusterRoleBindingSingular is the singular name for ClusterRoleBinding resources.
const ClusterRoleBindingSingular = "clusterrolebinding"

// ClusterRolePlural is the plural name for ClusterRole resources.
const ClusterRolePlural = "clusterroles"

// ClusterRoleSingular is the singular name for ClusterRole resources.
const ClusterRoleSingular = "clusterrole"

// RoleBindingPlural is the plural name for RoleBinding resources.
const RoleBindingPlural = "rolebindings"

// RoleBindingSingular is the singular name for RoleBinding resources.
const RoleBindingSingular = "rolebinding"

// RolePlural is the plural name for Role resources.
const RolePlural = "roles"

// RoleSingular is the singular name for Role resources.
const RoleSingular = "role"

var (
	// ClusterRoleBindingSchemaYAML contains the OpenAPI v3 schema for ClusterRoleBinding.
	//go:embed .schemas/clusterrolebinding_schema.yaml
	ClusterRoleBindingSchemaYAML string

	// ClusterRoleSchemaYAML contains the OpenAPI v3 schema for ClusterRole.
	//go:embed .schemas/clusterrole_schema.yaml
	ClusterRoleSchemaYAML string

	// RoleBindingSchemaYAML contains the OpenAPI v3 schema for RoleBinding.
	//go:embed .schemas/rolebinding_schema.yaml
	RoleBindingSchemaYAML string

	// RoleSchemaYAML contains the OpenAPI v3 schema for Role.
	//go:embed .schemas/role_schema.yaml
	RoleSchemaYAML string

)

var (
	// ClusterRoleBindingSchema is the parsed structural schema for ClusterRoleBinding.
	ClusterRoleBindingSchema *schema.Structural

	// ClusterRoleSchema is the parsed structural schema for ClusterRole.
	ClusterRoleSchema *schema.Structural

	// RoleBindingSchema is the parsed structural schema for RoleBinding.
	RoleBindingSchema *schema.Structural

	// RoleSchema is the parsed structural schema for Role.
	RoleSchema *schema.Structural
)

func init() {
	var err error

	// Parse ClusterRoleBinding schema
	var clusterrolebindingPropsV1 apiextv1.JSONSchemaProps
	if err := yaml.Unmarshal([]byte(ClusterRoleBindingSchemaYAML), &clusterrolebindingPropsV1); err != nil {
		panic("failed to unmarshal ClusterRoleBinding schema: " + err.Error())
	}
	var clusterrolebindingProps apiext.JSONSchemaProps
	if err := apiextv1.Convert_v1_JSONSchemaProps_To_apiextensions_JSONSchemaProps(&clusterrolebindingPropsV1, &clusterrolebindingProps, nil); err != nil {
		panic("failed to convert ClusterRoleBinding schema: " + err.Error())
	}
	ClusterRoleBindingSchema, err = schema.NewStructural(&clusterrolebindingProps)
	if err != nil {
		panic("failed to create structural schema for ClusterRoleBinding: " + err.Error())
	}

	// Parse ClusterRole schema
	var clusterrolePropsV1 apiextv1.JSONSchemaProps
	if err := yaml.Unmarshal([]byte(ClusterRoleSchemaYAML), &clusterrolePropsV1); err != nil {
		panic("failed to unmarshal ClusterRole schema: " + err.Error())
	}
	var clusterroleProps apiext.JSONSchemaProps
	if err := apiextv1.Convert_v1_JSONSchemaProps_To_apiextensions_JSONSchemaProps(&clusterrolePropsV1, &clusterroleProps, nil); err != nil {
		panic("failed to convert ClusterRole schema: " + err.Error())
	}
	ClusterRoleSchema, err = schema.NewStructural(&clusterroleProps)
	if err != nil {
		panic("failed to create structural schema for ClusterRole: " + err.Error())
	}

	// Parse RoleBinding schema
	var rolebindingPropsV1 apiextv1.JSONSchemaProps
	if err := yaml.Unmarshal([]byte(RoleBindingSchemaYAML), &rolebindingPropsV1); err != nil {
		panic("failed to unmarshal RoleBinding schema: " + err.Error())
	}
	var rolebindingProps apiext.JSONSchemaProps
	if err := apiextv1.Convert_v1_JSONSchemaProps_To_apiextensions_JSONSchemaProps(&rolebindingPropsV1, &rolebindingProps, nil); err != nil {
		panic("failed to convert RoleBinding schema: " + err.Error())
	}
	RoleBindingSchema, err = schema.NewStructural(&rolebindingProps)
	if err != nil {
		panic("failed to create structural schema for RoleBinding: " + err.Error())
	}

	// Parse Role schema
	var rolePropsV1 apiextv1.JSONSchemaProps
	if err := yaml.Unmarshal([]byte(RoleSchemaYAML), &rolePropsV1); err != nil {
		panic("failed to unmarshal Role schema: " + err.Error())
	}
	var roleProps apiext.JSONSchemaProps
	if err := apiextv1.Convert_v1_JSONSchemaProps_To_apiextensions_JSONSchemaProps(&rolePropsV1, &roleProps, nil); err != nil {
		panic("failed to convert Role schema: " + err.Error())
	}
	RoleSchema, err = schema.NewStructural(&roleProps)
	if err != nil {
		panic("failed to create structural schema for Role: " + err.Error())
	}
}

// GetResourceInfos returns ResourceInfo definitions for all types in this package.
// This can be used to configure an API server with these resources.
func GetResourceInfos() []types.ResourceInfo {
	return []types.ResourceInfo{
		{
			GVK:        GroupVersion.WithKind("ClusterRoleBinding"),
			Plural:     ClusterRoleBindingPlural,
			Singular:   ClusterRoleBindingSingular,
			SchemaYAML: ClusterRoleBindingSchemaYAML,
		},
		{
			GVK:        GroupVersion.WithKind("ClusterRole"),
			Plural:     ClusterRolePlural,
			Singular:   ClusterRoleSingular,
			SchemaYAML: ClusterRoleSchemaYAML,
		},
		{
			GVK:        GroupVersion.WithKind("RoleBinding"),
			Plural:     RoleBindingPlural,
			Singular:   RoleBindingSingular,
			SchemaYAML: RoleBindingSchemaYAML,
		},
		{
			GVK:        GroupVersion.WithKind("Role"),
			Plural:     RolePlural,
			Singular:   RoleSingular,
			SchemaYAML: RoleSchemaYAML,
		},
	}
}
