// Code generated by orlop-gen. DO NOT EDIT.

package v1

import (
	_ "embed"

	"github.com/thetechnick/orlop/pkg/apiserver/types"
)

var (
	// ObjectSchemaYAML contains the OpenAPI v3 schema for Object.
	//go:embed .schemas/object_schema.yaml
	ObjectSchemaYAML string

	// OtherSchemaYAML contains the OpenAPI v3 schema for Other.
	//go:embed .schemas/other_schema.yaml
	OtherSchemaYAML string

)

// ObjectResourceInfo describes the Object resource type.
var ObjectResourceInfo = types.ResourceInfo{
	GVK:        GroupVersion.WithKind("Object"),
	Plural:     "objects",
	Singular:   "object",
	Namespaced: true,
	SchemaYAML: ObjectSchemaYAML,
}

// OtherResourceInfo describes the Other resource type.
var OtherResourceInfo = types.ResourceInfo{
	GVK:        GroupVersion.WithKind("Other"),
	Plural:     "others",
	Singular:   "other",
	Namespaced: true,
	SchemaYAML: OtherSchemaYAML,
}

// GetResourceInfos returns ResourceInfo definitions for all types in this package.
// This can be used to configure an API server with these resources.
func GetResourceInfos() []types.ResourceInfo {
	return []types.ResourceInfo{
		ObjectResourceInfo,
		OtherResourceInfo,
	}
}
