package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"sync"

	"k8s.io/code-generator/cmd/conversion-gen/args"
	conversiongen "k8s.io/code-generator/cmd/conversion-gen/generators"
	"k8s.io/gengo/v2"
	"k8s.io/gengo/v2/generator"
	"k8s.io/gengo/v2/namer"
	"k8s.io/klog/v2"
)

var klogInitOnce sync.Once

// customConversionNamer creates unique function names by including more package path
// components to distinguish between internal and public packages
func customConversionNamer() *namer.NameStrategy {
	return &namer.NameStrategy{
		Join: func(pre string, in []string, post string) string {
			return strings.Join(in, "_")
		},
		// Use 3 package names to include "internal" or "public" in the path
		// e.g., "internal_test_v1" vs "public_test_v1"
		PrependPackageNames: 3,
	}
}

// customNameSystems returns custom name systems that avoid function name collisions
func customNameSystems() namer.NameSystems {
	return namer.NameSystems{
		"public":    customConversionNamer(),
		"raw":       namer.NewRawNamer("", nil),
		"defaultfn": &namer.NameStrategy{
			Prefix: "SetDefaults_",
			Join: func(pre string, in []string, post string) string {
				return pre + strings.Join(in, "_") + post
			},
		},
	}
}

func (g *Generator) generateConversions() error {
	// Find all package directories that need conversion generation
	var packagePaths []string

	err := filepath.Walk(g.outputDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}

		if !info.IsDir() {
			return nil
		}

		// Check if this directory has Go files (excluding generated)
		entries, err := os.ReadDir(path)
		if err != nil {
			return err
		}

		hasGoFiles := false
		for _, entry := range entries {
			if !entry.IsDir() && strings.HasSuffix(entry.Name(), ".go") && !strings.HasPrefix(entry.Name(), "zz_generated") {
				hasGoFiles = true
				break
			}
		}

		if hasGoFiles {
			// Get the package import path
			relPath, err := filepath.Rel(g.outputDir, path)
			if err != nil {
				return err
			}

			// Check if corresponding internal package exists
			internalPath := filepath.Join(g.inputDir, relPath)
			if _, err := os.Stat(internalPath); err == nil {
				pkgPath := "github.com/thetechnick/orlop/apis/public/" + strings.ReplaceAll(relPath, string(filepath.Separator), "/")
				packagePaths = append(packagePaths, pkgPath)

				// Create doc.go with conversion markers
				if err := g.createConversionDocFile(path, relPath); err != nil {
					return fmt.Errorf("failed to create doc.go: %w", err)
				}
			}
		}

		return nil
	})
	if err != nil {
		return fmt.Errorf("failed to walk output directory: %w", err)
	}

	if len(packagePaths) == 0 {
		return nil
	}

	// Use conversion-gen library directly
	for _, pkgPath := range packagePaths {
		if err := g.runConversionGenLib(pkgPath); err != nil {
			return fmt.Errorf("failed to generate conversions for %s: %w", pkgPath, err)
		}
	}

	return nil
}

func (g *Generator) createConversionDocFile(pkgDir, relPath string) error {
	// Get package name
	pkgName, err := determinePackageName(pkgDir)
	if err != nil {
		return err
	}

	// Construct internal package import path
	internalImportPath := "github.com/thetechnick/orlop/apis/internal/" + strings.ReplaceAll(relPath, string(filepath.Separator), "/")

	docContent := fmt.Sprintf(`// +k8s:conversion-gen=%s
// +k8s:conversion-gen-external-types=%s

// Package %s contains the public API types.
package %s
`, internalImportPath, internalImportPath, pkgName, pkgName)

	docPath := filepath.Join(pkgDir, "doc.go")
	return os.WriteFile(docPath, []byte(docContent), 0644)
}

func (g *Generator) runConversionGenLib(pkgPath string) error {
	// Initialize klog flags only once
	klogInitOnce.Do(func() {
		klog.InitFlags(nil)
	})

	// Get project root
	projectRoot := filepath.Dir(filepath.Dir(g.outputDir))

	// Set up args
	genArgs := args.New()
	genArgs.GoHeaderFile = filepath.Join(projectRoot, "hack/boilerplate.go.txt")
	// genArgs.GeneratedBuildTag is already set to "ignore_autogenerated" by New()
	genArgs.OutputFile = "zz_generated.conversion.go"

	// Create generator context with custom naming to avoid collisions
	myTargets := func(context *generator.Context) []generator.Target {
		return conversiongen.GetTargets(context, genArgs)
	}

	// Execute code generation with custom name systems
	// Note: We pass empty string for buildTag parameter because it's only used
	// for parser build tags. The output build tag comes from the boilerplate
	// generated in GetTargets via args.GeneratedBuildTag.
	if err := gengo.Execute(
		customNameSystems(), // Use custom name systems to avoid duplicate names
		conversiongen.DefaultNameSystem(),
		myTargets,
		"", // Don't pass buildTag here - it's for parser, not output
		[]string{pkgPath}, // Input packages
	); err != nil {
		return fmt.Errorf("gengo.Execute failed: %w", err)
	}

	// Post-process the generated file to fix duplicate function names
	// The issue is that conversion-gen generates both:
	// - Convert_v1_Object_To_v1_Object (from internal v1 to internal v1)
	// - Convert_v1_Object_To_v1_Object (from public v1 to public v1)
	// We need to rename one set to avoid conflicts
	if strings.Contains(pkgPath, "/apis/public/") {
		// Calculate the actual file path
		pkgRelPath := strings.TrimPrefix(pkgPath, "github.com/thetechnick/orlop/")
		genFilePath := filepath.Join(projectRoot, pkgRelPath, genArgs.OutputFile)
		fmt.Printf("  Post-processing %s to fix duplicate names...\n", genFilePath)
		if err := g.fixDuplicateConversionNames(genFilePath); err != nil {
			return fmt.Errorf("failed to fix duplicate names: %w", err)
		}
	}

	return nil
}

func (g *Generator) fixDuplicateConversionNames(filePath string) error {
	content, err := os.ReadFile(filePath)
	if err != nil {
		return err
	}

	// Replace duplicate function declarations by renaming the second occurrence
	// of each conversion function to include package distinction
	lines := strings.Split(string(content), "\n")
	seenFuncs := make(map[string]bool)
	var result []string
	inSecondDuplicate := false
	currentFunc := ""

	for i, line := range lines {
		// Check if this is a function declaration
		if strings.HasPrefix(strings.TrimSpace(line), "func autoConvert_") ||
			strings.HasPrefix(strings.TrimSpace(line), "func Convert_") {
			// Extract function name
			funcName := strings.TrimSpace(line)
			if idx := strings.Index(funcName, "("); idx > 0 {
				funcName = funcName[5:idx] // Remove "func "
			}

			if seenFuncs[funcName] {
				// This is a duplicate - rename it by adding suffix
				// Convert internal package functions to use "internal" prefix
				inSecondDuplicate = true
				currentFunc = funcName
				line = strings.Replace(line, funcName, funcName+"_internal", 1)
			} else {
				seenFuncs[funcName] = true
				inSecondDuplicate = false
			}
		} else if inSecondDuplicate {
			// Also update calls to renamed functions
			if currentFunc != "" {
				line = strings.ReplaceAll(line, currentFunc+"(", currentFunc+"_internal(")
			}
			// Check if we've reached the end of the function
			if strings.TrimSpace(line) == "}" && i > 0 {
				inSecondDuplicate = false
				currentFunc = ""
			}
		}

		result = append(result, line)
	}

	return os.WriteFile(filePath, []byte(strings.Join(result, "\n")), 0644)
}
