package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	apiextv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	"sigs.k8s.io/controller-tools/pkg/crd"
	"sigs.k8s.io/controller-tools/pkg/genall"
	"sigs.k8s.io/controller-tools/pkg/loader"
	"sigs.k8s.io/yaml"
)

type schemaInfo struct {
	typeName string
	plural   string
	schema   *apiextv1.JSONSchemaProps
}

func (g *Generator) generateSchemas(rootPath string) error {
	absPath, err := filepath.Abs(rootPath)
	if err != nil {
		return fmt.Errorf("failed to get absolute path: %w", err)
	}

	// Load packages
	roots, err := loader.LoadRoots(absPath + "/...")
	if err != nil {
		return fmt.Errorf("failed to load packages: %w", err)
	}

	if len(roots) == 0 {
		return nil
	}

	// Find packages with root types and get the directory where they're defined
	var hasRootTypes bool
	var versionedPkgDir string
	for _, root := range roots {
		root.NeedSyntax()
		for _, file := range root.Syntax {
			for _, comment := range file.Comments {
				if strings.Contains(comment.Text(), "+kubebuilder:object:root") {
					hasRootTypes = true
					versionedPkgDir = root.Dir
					break
				}
			}
			if hasRootTypes {
				break
			}
		}
		if hasRootTypes {
			break
		}
	}

	if !hasRootTypes {
		return nil
	}

	// Generate CRDs in the versioned directory where root types are defined
	crdOutputDir := versionedPkgDir
	if err := g.generateCRDs(roots, crdOutputDir); err != nil {
		return fmt.Errorf("failed to generate CRDs: %w", err)
	}

	// Extract schemas and embed them in the same directory
	if err := g.embedSchemas(crdOutputDir, crdOutputDir); err != nil {
		return fmt.Errorf("failed to embed schemas: %w", err)
	}

	return nil
}

func (g *Generator) generateCRDs(roots []*loader.Package, outputDir string) error {
	crdGen := crd.Generator{CRDVersions: []string{"v1"}}
	gen := genall.Generator(crdGen)
	generators := genall.Generators{&gen}

	// Create runtime
	runtime, err := generators.ForRoots(roots[0].PkgPath + "/...")
	if err != nil {
		return fmt.Errorf("failed to create runtime: %w", err)
	}

	runtime.OutputRules = genall.OutputRules{
		Default: genall.OutputToDirectory(outputDir),
	}
	runtime.ErrorWriter = os.Stderr

	runtime.Run()

	return nil
}

func (g *Generator) embedSchemas(crdDir string, targetDir string) error {
	var schemas []schemaInfo

	// Find all YAML CRD files in the CRD directory
	entries, err := os.ReadDir(crdDir)
	if err != nil {
		return fmt.Errorf("failed to read directory %s: %w", crdDir, err)
	}

	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".yaml") {
			continue
		}

		crdPath := filepath.Join(crdDir, entry.Name())

		// Read and parse CRD
		data, err := os.ReadFile(crdPath)
		if err != nil {
			return fmt.Errorf("failed to read CRD file %s: %w", crdPath, err)
		}

		var crd apiextv1.CustomResourceDefinition
		if err := yaml.Unmarshal(data, &crd); err != nil {
			return fmt.Errorf("failed to unmarshal CRD %s: %w", crdPath, err)
		}

		// Extract schema from first version
		if len(crd.Spec.Versions) == 0 {
			continue
		}

		version := crd.Spec.Versions[0]
		if version.Schema == nil || version.Schema.OpenAPIV3Schema == nil {
			continue
		}

		schemas = append(schemas, schemaInfo{
			typeName: crd.Spec.Names.Kind,
			plural:   crd.Spec.Names.Plural,
			schema:   version.Schema.OpenAPIV3Schema,
		})

		// Remove the YAML file after extracting schema
		if err := os.Remove(crdPath); err != nil {
			return fmt.Errorf("failed to remove CRD file %s: %w", crdPath, err)
		}
	}

	if len(schemas) == 0 {
		return nil
	}

	// Generate Go file with embedded schemas in the target directory
	goFilePath := filepath.Join(targetDir, "zz_generated.schemas.go")
	if err := g.generateSchemaGoFile(goFilePath, targetDir, schemas); err != nil {
		return fmt.Errorf("failed to generate schema Go file: %w", err)
	}

	return nil
}

func (g *Generator) generateSchemaGoFile(outputPath, packageDir string, schemas []schemaInfo) error {
	// Determine package name
	pkg, err := determinePackageName(packageDir)
	if err != nil {
		return fmt.Errorf("failed to determine package name: %w", err)
	}

	var source strings.Builder
	source.WriteString("// Code generated by orlop-gen. DO NOT EDIT.\n\n")
	source.WriteString("package " + pkg + "\n\n")
	source.WriteString("import (\n")
	source.WriteString("\t_ \"embed\"\n\n")
	source.WriteString(fmt.Sprintf("\t%q\n", g.typesImportPath))
	source.WriteString("\tapiext \"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions\"\n")
	source.WriteString("\tapiextv1 \"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1\"\n")
	source.WriteString("\t\"k8s.io/apiextensions-apiserver/pkg/apiserver/schema\"\n")
	source.WriteString("\t\"sigs.k8s.io/yaml\"\n")
	source.WriteString(")\n\n")

	// Generate constants for all schemas
	// Write schema files and generate embed directives
	schemasDir := filepath.Join(filepath.Dir(outputPath), ".schemas")
	if err := os.MkdirAll(schemasDir, 0755); err != nil {
		return fmt.Errorf("failed to create schemas directory: %w", err)
	}

	for _, s := range schemas {
		schemaYAML, err := yaml.Marshal(s.schema)
		if err != nil {
			return fmt.Errorf("failed to marshal schema for %s: %w", s.typeName, err)
		}

		// Write schema to separate file
		schemaFileName := fmt.Sprintf("%s_schema.yaml", strings.ToLower(s.typeName))
		schemaFilePath := filepath.Join(schemasDir, schemaFileName)
		if err := os.WriteFile(schemaFilePath, schemaYAML, 0644); err != nil {
			return fmt.Errorf("failed to write schema file for %s: %w", s.typeName, err)
		}

		// Plural name constant
		source.WriteString(fmt.Sprintf("// %sPlural is the plural name for %s resources.\n", s.typeName, s.typeName))
		source.WriteString(fmt.Sprintf("const %sPlural = %q\n\n", s.typeName, s.plural))
	}

	// Add go:embed directives and variables
	source.WriteString("var (\n")
	for _, s := range schemas {
		source.WriteString(fmt.Sprintf("\t// %sSchemaYAML contains the OpenAPI v3 schema for %s.\n", s.typeName, s.typeName))
		source.WriteString(fmt.Sprintf("\t//go:embed .schemas/%s_schema.yaml\n", strings.ToLower(s.typeName)))
		source.WriteString(fmt.Sprintf("\t%sSchemaYAML string\n\n", s.typeName))
	}
	source.WriteString(")\n\n")

	// Generate variables
	source.WriteString("var (\n")
	for i, s := range schemas {
		source.WriteString(fmt.Sprintf("\t// %sSchema is the parsed structural schema for %s.\n", s.typeName, s.typeName))
		source.WriteString(fmt.Sprintf("\t%sSchema *schema.Structural\n", s.typeName))
		if i < len(schemas)-1 {
			source.WriteString("\n")
		}
	}
	source.WriteString(")\n\n")

	// Generate init function
	source.WriteString("func init() {\n")
	source.WriteString("\tvar err error\n\n")

	for i, s := range schemas {
		varName := strings.ToLower(s.typeName)
		source.WriteString(fmt.Sprintf("\t// Parse %s schema\n", s.typeName))
		source.WriteString(fmt.Sprintf("\tvar %sPropsV1 apiextv1.JSONSchemaProps\n", varName))
		source.WriteString(fmt.Sprintf("\tif err := yaml.Unmarshal([]byte(%sSchemaYAML), &%sPropsV1); err != nil {\n", s.typeName, varName))
		source.WriteString(fmt.Sprintf("\t\tpanic(\"failed to unmarshal %s schema: \" + err.Error())\n", s.typeName))
		source.WriteString("\t}\n")
		source.WriteString(fmt.Sprintf("\tvar %sProps apiext.JSONSchemaProps\n", varName))
		source.WriteString(fmt.Sprintf("\tif err := apiextv1.Convert_v1_JSONSchemaProps_To_apiextensions_JSONSchemaProps(&%sPropsV1, &%sProps, nil); err != nil {\n", varName, varName))
		source.WriteString(fmt.Sprintf("\t\tpanic(\"failed to convert %s schema: \" + err.Error())\n", s.typeName))
		source.WriteString("\t}\n")
		source.WriteString(fmt.Sprintf("\t%sSchema, err = schema.NewStructural(&%sProps)\n", s.typeName, varName))
		source.WriteString("\tif err != nil {\n")
		source.WriteString(fmt.Sprintf("\t\tpanic(\"failed to create structural schema for %s: \" + err.Error())\n", s.typeName))
		source.WriteString("\t}\n")

		if i < len(schemas)-1 {
			source.WriteString("\n")
		}
	}
	source.WriteString("}\n\n")

	// Generate GetResourceInfos function
	source.WriteString("// GetResourceInfos returns ResourceInfo definitions for all types in this package.\n")
	source.WriteString("// This can be used to configure an API server with these resources.\n")
	source.WriteString("func GetResourceInfos() []types.ResourceInfo {\n")
	source.WriteString("\treturn []types.ResourceInfo{\n")

	for _, s := range schemas {
		source.WriteString("\t\t{\n")
		source.WriteString(fmt.Sprintf("\t\t\tGVK:        GroupVersion.WithKind(%q),\n", s.typeName))
		source.WriteString(fmt.Sprintf("\t\t\tPlural:     %sPlural,\n", s.typeName))
		source.WriteString(fmt.Sprintf("\t\t\tSchemaYAML: %sSchemaYAML,\n", s.typeName))
		source.WriteString("\t\t},\n")
	}

	source.WriteString("\t}\n")
	source.WriteString("}\n")

	// Write to file
	if err := os.WriteFile(outputPath, []byte(source.String()), 0644); err != nil {
		return fmt.Errorf("failed to write Go file: %w", err)
	}

	return nil
}

func determinePackageName(dir string) (string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return "", err
	}

	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") {
			continue
		}

		if strings.HasPrefix(entry.Name(), "zz_generated") {
			continue
		}

		filePath := filepath.Join(dir, entry.Name())
		data, err := os.ReadFile(filePath)
		if err != nil {
			continue
		}

		lines := strings.Split(string(data), "\n")
		for _, line := range lines {
			line = strings.TrimSpace(line)
			if strings.HasPrefix(line, "package ") {
				parts := strings.Fields(line)
				if len(parts) >= 2 {
					return parts[1], nil
				}
			}
		}
	}

	return "", fmt.Errorf("could not determine package name from directory %s", dir)
}

func determineGroupVersion(dir string) (group, version string, err error) {
	// Look for groupversion_info.go file in current directory
	groupVersionFile := filepath.Join(dir, "groupversion_info.go")
	data, err := os.ReadFile(groupVersionFile)

	// If not found in current dir, try looking in subdirectories (e.g., v1/)
	if err != nil {
		// Try finding it in a versioned subdirectory
		entries, readErr := os.ReadDir(dir)
		if readErr == nil {
			for _, entry := range entries {
				if entry.IsDir() && strings.HasPrefix(entry.Name(), "v") {
					versionedFile := filepath.Join(dir, entry.Name(), "groupversion_info.go")
					data, err = os.ReadFile(versionedFile)
					if err == nil {
						groupVersionFile = versionedFile
						break
					}
				}
			}
		}

		// If still not found, return error
		if err != nil {
			return "", "", fmt.Errorf("failed to read groupversion_info.go: %w", err)
		}
	}

	content := string(data)

	// Look for Group: "..." pattern
	if idx := strings.Index(content, `Group:`); idx != -1 {
		afterGroup := content[idx+6:]
		// Find the quoted string
		if startQuote := strings.Index(afterGroup, `"`); startQuote != -1 {
			afterStart := afterGroup[startQuote+1:]
			if endQuote := strings.Index(afterStart, `"`); endQuote != -1 {
				group = afterStart[:endQuote]
			}
		}
	}

	// Look for Version: "..." pattern
	if idx := strings.Index(content, `Version:`); idx != -1 {
		afterVersion := content[idx+8:]
		// Find the quoted string
		if startQuote := strings.Index(afterVersion, `"`); startQuote != -1 {
			afterStart := afterVersion[startQuote+1:]
			if endQuote := strings.Index(afterStart, `"`); endQuote != -1 {
				version = afterStart[:endQuote]
			}
		}
	}

	if group == "" || version == "" {
		return "", "", fmt.Errorf("could not determine group/version from %s (group=%q, version=%q)", groupVersionFile, group, version)
	}

	return group, version, nil
}
