// Code generated by orlop-gen. DO NOT EDIT.

package v1

import (
	privatev1 "github.com/thetechnick/orlop/apis/private/test/v1"
	"github.com/thetechnick/orlop/pkg/apiserver/types"
	runtimeschema "k8s.io/apimachinery/pkg/runtime/schema"
)

// Re-export constants from private API for convenience
const (
	ObjectPlural = privatev1.ObjectPlural
	OtherPlural  = privatev1.OtherPlural
)

// Re-export schema YAML from private API
const (
	ObjectSchemaYAML = privatev1.ObjectSchemaYAML
	OtherSchemaYAML  = privatev1.OtherSchemaYAML
)

// GetResourceInfos returns ResourceInfo definitions for all types in this package.
// This can be used to configure an API server with these resources.
func GetResourceInfos() []types.ResourceInfo {
	return []types.ResourceInfo{
		{
			GVK: runtimeschema.GroupVersionKind{
				Group:   "test.orlop.thetechnick.ninja",
				Version: "v1",
				Kind:    "Object",
			},
			Plural:     ObjectPlural,
			SchemaYAML: ObjectSchemaYAML,
		},
		{
			GVK: runtimeschema.GroupVersionKind{
				Group:   "test.orlop.thetechnick.ninja",
				Version: "v1",
				Kind:    "Other",
			},
			Plural:     OtherPlural,
			SchemaYAML: OtherSchemaYAML,
		},
	}
}
