//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by orlop-gen. DO NOT EDIT.

package v1

import (
	unsafe "unsafe"

	testv1 "github.com/thetechnick/orlop/apis/private/test/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*testv1.Object)(nil), (*testv1.Object)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Object_To_v1_Object(a.(*testv1.Object), b.(*testv1.Object), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*testv1.Object)(nil), (*testv1.Object)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Object_To_v1_Object(a.(*testv1.Object), b.(*testv1.Object), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*testv1.ObjectList)(nil), (*testv1.ObjectList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ObjectList_To_v1_ObjectList(a.(*testv1.ObjectList), b.(*testv1.ObjectList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*testv1.ObjectList)(nil), (*testv1.ObjectList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ObjectList_To_v1_ObjectList(a.(*testv1.ObjectList), b.(*testv1.ObjectList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*testv1.ObjectNested)(nil), (*testv1.ObjectNested)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ObjectNested_To_v1_ObjectNested(a.(*testv1.ObjectNested), b.(*testv1.ObjectNested), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*testv1.ObjectNested)(nil), (*testv1.ObjectNested)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ObjectNested_To_v1_ObjectNested(a.(*testv1.ObjectNested), b.(*testv1.ObjectNested), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*testv1.ObjectSpec)(nil), (*testv1.ObjectSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ObjectSpec_To_v1_ObjectSpec(a.(*testv1.ObjectSpec), b.(*testv1.ObjectSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*testv1.ObjectSpec)(nil), (*testv1.ObjectSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ObjectSpec_To_v1_ObjectSpec(a.(*testv1.ObjectSpec), b.(*testv1.ObjectSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*testv1.ObjectStatus)(nil), (*testv1.ObjectStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ObjectStatus_To_v1_ObjectStatus(a.(*testv1.ObjectStatus), b.(*testv1.ObjectStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*testv1.ObjectStatus)(nil), (*testv1.ObjectStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ObjectStatus_To_v1_ObjectStatus(a.(*testv1.ObjectStatus), b.(*testv1.ObjectStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*testv1.Other)(nil), (*testv1.Other)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Other_To_v1_Other(a.(*testv1.Other), b.(*testv1.Other), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*testv1.Other)(nil), (*testv1.Other)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Other_To_v1_Other(a.(*testv1.Other), b.(*testv1.Other), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*testv1.OtherList)(nil), (*testv1.OtherList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_OtherList_To_v1_OtherList(a.(*testv1.OtherList), b.(*testv1.OtherList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*testv1.OtherList)(nil), (*testv1.OtherList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_OtherList_To_v1_OtherList(a.(*testv1.OtherList), b.(*testv1.OtherList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*testv1.OtherSpec)(nil), (*testv1.OtherSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_OtherSpec_To_v1_OtherSpec(a.(*testv1.OtherSpec), b.(*testv1.OtherSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*testv1.OtherSpec)(nil), (*testv1.OtherSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_OtherSpec_To_v1_OtherSpec(a.(*testv1.OtherSpec), b.(*testv1.OtherSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*testv1.OtherStatus)(nil), (*testv1.OtherStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_OtherStatus_To_v1_OtherStatus(a.(*testv1.OtherStatus), b.(*testv1.OtherStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*testv1.OtherStatus)(nil), (*testv1.OtherStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_OtherStatus_To_v1_OtherStatus(a.(*testv1.OtherStatus), b.(*testv1.OtherStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1_Object_To_v1_Object(in *testv1.Object, out *testv1.Object, s conversion.Scope) error {
	out.TypeMeta = in.TypeMeta
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	out.Status = in.Status
	return nil
}

// Convert_v1_Object_To_v1_Object is an autogenerated conversion function.
func Convert_v1_Object_To_v1_Object(in *testv1.Object, out *testv1.Object, s conversion.Scope) error {
	return autoConvert_v1_Object_To_v1_Object(in, out, s)
}

func autoConvert_v1_Object_To_v1_Object_internal(in *testv1.Object, out *testv1.Object, s conversion.Scope) error {
	out.TypeMeta = in.TypeMeta
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	out.Status = in.Status
	return nil
}

// Convert_v1_Object_To_v1_Object is an autogenerated conversion function.
func Convert_v1_Object_To_v1_Object_internal(in *testv1.Object, out *testv1.Object, s conversion.Scope) error {
	return autoConvert_v1_Object_To_v1_Object_internal(in, out, s)
}

func autoConvert_v1_ObjectList_To_v1_ObjectList(in *testv1.ObjectList, out *testv1.ObjectList, s conversion.Scope) error {
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	out.Items = *(*[]testv1.Object)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_ObjectList_To_v1_ObjectList is an autogenerated conversion function.
func Convert_v1_ObjectList_To_v1_ObjectList(in *testv1.ObjectList, out *testv1.ObjectList, s conversion.Scope) error {
	return autoConvert_v1_ObjectList_To_v1_ObjectList(in, out, s)
}

func autoConvert_v1_ObjectList_To_v1_ObjectList_internal(in *testv1.ObjectList, out *testv1.ObjectList, s conversion.Scope) error {
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	out.Items = *(*[]testv1.Object)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_ObjectList_To_v1_ObjectList is an autogenerated conversion function.
func Convert_v1_ObjectList_To_v1_ObjectList_internal(in *testv1.ObjectList, out *testv1.ObjectList, s conversion.Scope) error {
	return autoConvert_v1_ObjectList_To_v1_ObjectList_internal(in, out, s)
}

func autoConvert_v1_ObjectNested_To_v1_ObjectNested(in *testv1.ObjectNested, out *testv1.ObjectNested, s conversion.Scope) error {
	out.PublicField = in.PublicField
	out.InternalField = in.InternalField
	return nil
}

// Convert_v1_ObjectNested_To_v1_ObjectNested is an autogenerated conversion function.
func Convert_v1_ObjectNested_To_v1_ObjectNested(in *testv1.ObjectNested, out *testv1.ObjectNested, s conversion.Scope) error {
	return autoConvert_v1_ObjectNested_To_v1_ObjectNested(in, out, s)
}

func autoConvert_v1_ObjectNested_To_v1_ObjectNested_internal(in *testv1.ObjectNested, out *testv1.ObjectNested, s conversion.Scope) error {
	out.PublicField = in.PublicField
	out.InternalField = in.InternalField
	return nil
}

// Convert_v1_ObjectNested_To_v1_ObjectNested is an autogenerated conversion function.
func Convert_v1_ObjectNested_To_v1_ObjectNested_internal(in *testv1.ObjectNested, out *testv1.ObjectNested, s conversion.Scope) error {
	return autoConvert_v1_ObjectNested_To_v1_ObjectNested_internal(in, out, s)
}

func autoConvert_v1_ObjectSpec_To_v1_ObjectSpec(in *testv1.ObjectSpec, out *testv1.ObjectSpec, s conversion.Scope) error {
	out.PublicField = in.PublicField
	out.InternalField = in.InternalField
	out.Nested = in.Nested
	out.DefaultField = in.DefaultField
	return nil
}

// Convert_v1_ObjectSpec_To_v1_ObjectSpec is an autogenerated conversion function.
func Convert_v1_ObjectSpec_To_v1_ObjectSpec(in *testv1.ObjectSpec, out *testv1.ObjectSpec, s conversion.Scope) error {
	return autoConvert_v1_ObjectSpec_To_v1_ObjectSpec(in, out, s)
}

func autoConvert_v1_ObjectSpec_To_v1_ObjectSpec_internal(in *testv1.ObjectSpec, out *testv1.ObjectSpec, s conversion.Scope) error {
	out.PublicField = in.PublicField
	out.InternalField = in.InternalField
	out.Nested = in.Nested
	out.DefaultField = in.DefaultField
	return nil
}

// Convert_v1_ObjectSpec_To_v1_ObjectSpec is an autogenerated conversion function.
func Convert_v1_ObjectSpec_To_v1_ObjectSpec_internal(in *testv1.ObjectSpec, out *testv1.ObjectSpec, s conversion.Scope) error {
	return autoConvert_v1_ObjectSpec_To_v1_ObjectSpec_internal(in, out, s)
}

func autoConvert_v1_ObjectStatus_To_v1_ObjectStatus(in *testv1.ObjectStatus, out *testv1.ObjectStatus, s conversion.Scope) error {
	out.Conditions = *(*[]string)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1_ObjectStatus_To_v1_ObjectStatus is an autogenerated conversion function.
func Convert_v1_ObjectStatus_To_v1_ObjectStatus(in *testv1.ObjectStatus, out *testv1.ObjectStatus, s conversion.Scope) error {
	return autoConvert_v1_ObjectStatus_To_v1_ObjectStatus(in, out, s)
}

func autoConvert_v1_ObjectStatus_To_v1_ObjectStatus_internal(in *testv1.ObjectStatus, out *testv1.ObjectStatus, s conversion.Scope) error {
	out.Conditions = *(*[]string)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1_ObjectStatus_To_v1_ObjectStatus is an autogenerated conversion function.
func Convert_v1_ObjectStatus_To_v1_ObjectStatus_internal(in *testv1.ObjectStatus, out *testv1.ObjectStatus, s conversion.Scope) error {
	return autoConvert_v1_ObjectStatus_To_v1_ObjectStatus_internal(in, out, s)
}

func autoConvert_v1_Other_To_v1_Other(in *testv1.Other, out *testv1.Other, s conversion.Scope) error {
	out.TypeMeta = in.TypeMeta
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	out.Status = in.Status
	return nil
}

// Convert_v1_Other_To_v1_Other is an autogenerated conversion function.
func Convert_v1_Other_To_v1_Other(in *testv1.Other, out *testv1.Other, s conversion.Scope) error {
	return autoConvert_v1_Other_To_v1_Other(in, out, s)
}

func autoConvert_v1_Other_To_v1_Other_internal(in *testv1.Other, out *testv1.Other, s conversion.Scope) error {
	out.TypeMeta = in.TypeMeta
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	out.Status = in.Status
	return nil
}

// Convert_v1_Other_To_v1_Other is an autogenerated conversion function.
func Convert_v1_Other_To_v1_Other_internal(in *testv1.Other, out *testv1.Other, s conversion.Scope) error {
	return autoConvert_v1_Other_To_v1_Other_internal(in, out, s)
}

func autoConvert_v1_OtherList_To_v1_OtherList(in *testv1.OtherList, out *testv1.OtherList, s conversion.Scope) error {
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	out.Items = *(*[]testv1.Other)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_OtherList_To_v1_OtherList is an autogenerated conversion function.
func Convert_v1_OtherList_To_v1_OtherList(in *testv1.OtherList, out *testv1.OtherList, s conversion.Scope) error {
	return autoConvert_v1_OtherList_To_v1_OtherList(in, out, s)
}

func autoConvert_v1_OtherList_To_v1_OtherList_internal(in *testv1.OtherList, out *testv1.OtherList, s conversion.Scope) error {
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	out.Items = *(*[]testv1.Other)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_OtherList_To_v1_OtherList is an autogenerated conversion function.
func Convert_v1_OtherList_To_v1_OtherList_internal(in *testv1.OtherList, out *testv1.OtherList, s conversion.Scope) error {
	return autoConvert_v1_OtherList_To_v1_OtherList_internal(in, out, s)
}

func autoConvert_v1_OtherSpec_To_v1_OtherSpec(in *testv1.OtherSpec, out *testv1.OtherSpec, s conversion.Scope) error {
	out.PublicField = in.PublicField
	out.InternalField = in.InternalField
	return nil
}

// Convert_v1_OtherSpec_To_v1_OtherSpec is an autogenerated conversion function.
func Convert_v1_OtherSpec_To_v1_OtherSpec(in *testv1.OtherSpec, out *testv1.OtherSpec, s conversion.Scope) error {
	return autoConvert_v1_OtherSpec_To_v1_OtherSpec(in, out, s)
}

func autoConvert_v1_OtherSpec_To_v1_OtherSpec_internal(in *testv1.OtherSpec, out *testv1.OtherSpec, s conversion.Scope) error {
	out.PublicField = in.PublicField
	out.InternalField = in.InternalField
	return nil
}

// Convert_v1_OtherSpec_To_v1_OtherSpec is an autogenerated conversion function.
func Convert_v1_OtherSpec_To_v1_OtherSpec_internal(in *testv1.OtherSpec, out *testv1.OtherSpec, s conversion.Scope) error {
	return autoConvert_v1_OtherSpec_To_v1_OtherSpec_internal(in, out, s)
}

func autoConvert_v1_OtherStatus_To_v1_OtherStatus(in *testv1.OtherStatus, out *testv1.OtherStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1_OtherStatus_To_v1_OtherStatus is an autogenerated conversion function.
func Convert_v1_OtherStatus_To_v1_OtherStatus(in *testv1.OtherStatus, out *testv1.OtherStatus, s conversion.Scope) error {
	return autoConvert_v1_OtherStatus_To_v1_OtherStatus(in, out, s)
}

func autoConvert_v1_OtherStatus_To_v1_OtherStatus_internal(in *testv1.OtherStatus, out *testv1.OtherStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1_OtherStatus_To_v1_OtherStatus is an autogenerated conversion function.
func Convert_v1_OtherStatus_To_v1_OtherStatus_internal(in *testv1.OtherStatus, out *testv1.OtherStatus, s conversion.Scope) error {
	return autoConvert_v1_OtherStatus_To_v1_OtherStatus_internal(in, out, s)
}
